Repository cert-manager/cmctl, pull requests merged in 2025-08, with the labels that each got.

#269 Bump helm to address reported vulns
  go.mod
  go.sum
Labels: dco-signoff: yes, size/S, lgtm, approved

#274 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/boilerplate/01_mod.mk
  make/_shared/boilerplate/base/LICENSE
  make/_shared/executable/00_mod.mk
  make/_shared/executable/01_mod.mk
  make/_shared/go/01_mod.mk
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#283 Migrate away from archived github.com/google/gofuzz
  go.mod
  test/integration/testdata/apis/testgroup/fuzzer/fuzzer.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#287 Manual self-upgrade
  .github/workflows/renovate.yaml
  klone.yaml
  make/_shared/repository-base/base-dependabot/.github/workflows/renovate.yaml
  make/_shared/tools/00_mod.mk
  test/integration/testdata/apis/testgroup/crds/testgroup.testing.cert-manager.io_testtypes.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved
