Repository cert-manager/cmctl, pull requests merged in 2025-04, with the labels that each got.

#205 Bump cert-manager dependency to 1.17.x
  .gitignore
  go.mod
  go.sum
  pkg/convert/convert.go
  pkg/convert/internal/apis/acme/types_issuer.go
  pkg/convert/internal/apis/acme/v1/zz_generated.conversion.go
  pkg/convert/internal/apis/acme/v1alpha2/types_issuer.go
  pkg/convert/internal/apis/acme/v1alpha2/zz_generated.conversion.go
  pkg/convert/internal/apis/acme/v1alpha3/types_issuer.go
  pkg/convert/internal/apis/acme/v1alpha3/zz_generated.conversion.go
  pkg/convert/internal/apis/acme/v1beta1/types_issuer.go
  pkg/convert/internal/apis/acme/v1beta1/zz_generated.conversion.go
  pkg/convert/internal/apis/certmanager/types_certificate.go
  pkg/convert/internal/apis/certmanager/v1/zz_generated.conversion.go
  pkg/convert/internal/apis/certmanager/v1alpha2/types_certificate.go
  pkg/convert/internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  pkg/convert/internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go
  pkg/convert/internal/apis/certmanager/v1alpha3/types_certificate.go
  pkg/convert/internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  pkg/convert/internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go
  pkg/convert/internal/apis/certmanager/v1beta1/types_certificate.go
  pkg/convert/internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  pkg/convert/internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go
  pkg/convert/internal/apis/certmanager/zz_generated.deepcopy.go
  test/integration/ctl_convert_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#215 Bump containerd to patch CVE-2024-40635
  go.mod
  go.sum
Labels: dco-signoff: yes, size/S, lgtm, approved, needs-ok-to-test

#216 Add distributed releases to README.md
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS

#222 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved
